channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=24.1
- pip:
  - mlflow==2.4
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - pandas==2.2.2
  - scikit-learn==1.2.2
  - scipy==1.13.1
  - xgboost==2.1.0
name: mlflow-env
